---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  mysql-custom.cnf: |-
    [mysqld]
    server_id=1
    binlog_format=ROW
    binlog_rows_query_log_events=true
    max_binlog_size=40960
    log-bin=/var/lib/mysql/mysql
  grants.sql: |-
    CREATE TABLE test.test (id INT AUTO_INCREMENT PRIMARY KEY NOT NULL);
    GRANT REPLICATION CLIENT ON *.* TO 'binlogik'@'%';
    GRANT REPLICATION SLAVE ON *.* TO 'binlogik'@'%';
    GRANT SELECT ON *.* TO 'binlogik'@'%';
