---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  mysql-custom.cnf: |-
    [mysqld]
    server_id=1
    binlog_format=ROW
    binlog_rows_query_log_events=true
    expire_logs_days=1
    log-bin=/var/lib/mysql/mysql
    max_binlog_size=1048576
    gtid_mode=ON
    enforce_gtid_consistency=ON 
    init_connect=SET collation_connection = utf8mb4_unicode_ci
    character-set-server = utf8mb4
    collation-server = utf8mb4_unicode_ci
    #ignore-db-dir=lost+found
    #binlog_cache_size=16384
    #max_binlog_cache_size=32768
    #binlog_stmt_cache_size=16384
    #max_binlog_stmt_cache_size=32768
  grants.sql: |-
    CREATE TABLE test.test (id INT AUTO_INCREMENT PRIMARY KEY NOT NULL, created_at DATETIME NOT NULL, description TEXT NOT NULL, extra BLOB NOT NULL);
    GRANT REPLICATION CLIENT ON *.* TO 'binlogik'@'%';
    GRANT REPLICATION SLAVE ON *.* TO 'binlogik'@'%';
    GRANT SELECT ON *.* TO 'binlogik'@'%';
    PURGE BINARY LOGS BEFORE (DATE(NOW()) + INTERVAL 0 SECOND);
