---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: binlogik
  name: binlogik
spec:
  hostNetwork: true
  containers:
  - args:
    - bundle
    - exec
    - binlogik
    stdin: false
    stdinOnce: false
    tty: false
    image: mysql2-binlog-stream:latest
    imagePullPolicy: IfNotPresent
    name: binlogik
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /home/app/tmp
      name: tmpdir
  - args:
    - bundle
    - exec
    - rackup
    - config.ru
    stdin: false
    stdinOnce: false
    tty: false
    image: mysql2-binlog-stream:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 9292
      name: metrics
      hostPort: 9292
    livenessProbe:
      exec:
        command:
        - "/bin/true"
      initialDelaySeconds: 1
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3
    readinessProbe:
      exec:
        command:
        - "/bin/true"
      initialDelaySeconds: 1
      periodSeconds: 10
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 3
    name: metrics
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /home/app/tmp
      name: tmpdir
  restartPolicy: Never
  securityContext: {}
  terminationGracePeriodSeconds: 1
  volumes:
  - name: tmpdir
    emptyDir: {}
